### PR TITLE
Fixed support for integer keys

### LINKED ISSUE #3: Missing support for integer array keys
[Here](https://github.com/Dhii/container-helper-base/blob/v0.1-alpha1/src/ContainerGetCapableTrait.php#L45) and [here](https://github.com/Dhii/container-helper-base/blob/v0.1-alpha1/src/ContainerHasCapableTrait.php#L40) the key is indiscriminately normalized to string. This makes it impossible to access numeric array keys.

I would suggest string normalization only for non-array containers. For arrays, normalize to string only if the key is not an `int`.

### PR DESCRIPTION
**Pull request by mecha**
Fixes #3 and #2

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Achieved maintainability rating of "A".

File: src/ContainerGetCapableTrait.php [hunk 1]
```diff
@@ -32,50 +23,77 @@
...
-                $this->__('Argument #1 is not a valid container'),
-                null,
-                null,
-                $container
-            );
+        $origKey = $key;
+        $key     = $this->_normalizeString($key);
+        // NotFoundExceptionInterface#getDataKey() returns `string` or `Stringable`,
+        // so normalize only other types, and preserve original
+        $origKey = is_string($key) || $key instanceof Stringable
```
Comment (mecha) [inline src/ContainerGetCapableTrait.php]: The `$key` is being normalized to a string (_line 37_).  
This means all scalar values will become strings and `Stringable` instances will be reduced to strings. In other words, all non-null values of `$key` result in `$key` becoming a string.

As such, this condition will never fail for non-null values, making `$origKey` always equal itself.

Is this intended? Or was there some other intended purpose of this check?

Comment (XedinUnknown) [reply src/ContainerGetCapableTrait.php]: Didn't quite understand. `$origKey` will equal itself if it is a `string` or `Stringable`. Everything else gets normalized. Or am I missing something?

Comment (mecha) [reply src/ContainerGetCapableTrait.php]:
````

Comment (mecha) [reply src/ContainerGetCapableTrait.php]:
````

Comment (mecha) [reply src/ContainerGetCapableTrait.php]:
```
// origKey | value: unknown | type: mixed
// key     | value: unknown | type: mixed
$origKey = key;

// origKey | value: unknown | type: mixed
// key     | value: unknown | type: string
$key = $this->_normalizeString($key);

// origKey | value: unknown | type: mixed
// key     | value: unknown | TYPE: STRING
$origKey = is_string($key) || $key instanceof Stringable
    ? $origKey // This will always happen.
    : $key;    // This will never happen.
```

Comment (XedinUnknown) [reply src/ContainerGetCapableTrait.php]: Good point.

**Comment by mecha** [comment]
Always be yourself.

**Comment by XedinUnknown** [comment]
Unless you can be a key. Then always be a key.

**Comment by XedinUnknown** [comment]
Is this good to merge?

**Comment by mecha** [comment]
LGTM. You?

**Review by XedinUnknown — APPROVED** [review]
